import type { TerminalPalette, TerminalTheme } from "./types";

export const THEME_PRESETS = new Map<string, TerminalPalette>([
  [
    "dark",
    {
      name: "Dark",
      kind: "dark",
      background: "#000000",
      foreground: "#d7e0ea",
      cursor: "#d7e0ea",
      selectionBackground: "#2f5f91",
      black: "#101820",
      red: "#ff6b7a",
      green: "#7bd88f",
      yellow: "#f7c76b",
      blue: "#6ccff6",
      magenta: "#c792ea",
      cyan: "#5de4c7",
      white: "#d7e0ea",
      brightBlack: "#52677a",
      brightRed: "#ff8fa0",
      brightGreen: "#a5f3b1",
      brightYellow: "#ffe08a",
      brightBlue: "#9adfff",
      brightMagenta: "#d6a9ff",
      brightCyan: "#8df2dc",
      brightWhite: "#f0f4f8",
    },
  ],
  [
    "highContrast",
    {
      name: "High Contrast",
      kind: "dark",
      background: "#000000",
      foreground: "#ffffff",
      cursor: "#ffffff",
      selectionBackground: "#345f9f",
      black: "#000000",
      red: "#ff5c57",
      green: "#5af78e",
      yellow: "#f3f99d",
      blue: "#57c7ff",
      magenta: "#ff6ac1",
      cyan: "#9aedfe",
      white: "#f1f1f0",
      brightBlack: "#686868",
      brightRed: "#ff5c57",
      brightGreen: "#5af78e",
      brightYellow: "#f3f99d",
      brightBlue: "#57c7ff",
      brightMagenta: "#ff6ac1",
      brightCyan: "#9aedfe",
      brightWhite: "#ffffff",
    },
  ],
  [
    "soft",
    {
      name: "Soft Dark",
      kind: "dark",
      background: "#080d12",
      foreground: "#d8dee9",
      cursor: "#e5edf5",
      selectionBackground: "#334b5f",
      black: "#1b2632",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#d19a66",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#d8dee9",
      brightBlack: "#607080",
      brightRed: "#ef7b84",
      brightGreen: "#a7d388",
      brightYellow: "#e0aa75",
      brightBlue: "#70befd",
      brightMagenta: "#d587ec",
      brightCyan: "#65c5d1",
      brightWhite: "#eef4fb",
    },
  ],
  [
    "light",
    {
      name: "Light",
      kind: "light",
      background: "#FFFFFF",
      foreground: "#2d3748",
      cursor: "#2d3748",
      selectionBackground: "#bee3f8",
      black: "#1a202c",
      red: "#e53e3e",
      green: "#38a169",
      yellow: "#d69e2e",
      blue: "#3182ce",
      magenta: "#d53f8c",
      cyan: "#319795",
      white: "#e2e8f0",
      brightBlack: "#718096",
      brightRed: "#e53e3e",
      brightGreen: "#38a169",
      brightYellow: "#d69e2e",
      brightBlue: "#3182ce",
      brightMagenta: "#d53f8c",
      brightCyan: "#319795",
      brightWhite: "#edf2f7",
    },
  ],
  [
    "solarizedLight",
    {
      name: "Solarized Light",
      kind: "light",
      background: "#fdf6e3",
      foreground: "#657b83",
      cursor: "#657b83",
      selectionBackground: "#eee8d5",
      black: "#07362f",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  ],
  [
    "catppuccinLatte",
    {
      name: "Catppuccin Latte",
      kind: "light",
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      selectionBackground: "#acb0be",
      black: "#4c4f69",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#e6e9ef",
      brightBlack: "#bcc0cc",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#ea76cb",
      brightCyan: "#179299",
      brightWhite: "#dce0e8",
    },
  ],
  [
    "tokyoNight",
    {
      name: "Tokyo Night",
      kind: "dark",
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      selectionBackground: "#33467c",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  ],
  [
    "dracula",
    {
      name: "Dracula",
      kind: "dark",
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#6272a4",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff5555",
      brightGreen: "#50fa7b",
      brightYellow: "#f1fa8c",
      brightBlue: "#8590b5",
      brightMagenta: "#ff79c6",
      brightCyan: "#8be9fd",
      brightWhite: "#ffffff",
    },
  ],
]);

export function getThemePalette(theme: TerminalTheme): TerminalPalette {
  if (theme && theme.preset === "custom") {
    return (theme as { preset: "custom"; palette: TerminalPalette }).palette;
  }
  let presetKey = (theme && theme.preset) || "system";
  if (presetKey === "system") {
    const isDark = typeof window !== "undefined" && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
    presetKey = isDark ? "dark" : "light";
  }
  const preset = THEME_PRESETS.get(presetKey) || THEME_PRESETS.get("dark");
  if (!preset) {
    throw new Error("Default preset theme not found");
  }
  return preset;
}
